# Generated by Django 5.2.9 on 2025-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="attributes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
