# Generated by Django 5.2.9 on 2025-12-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0002_orderitem_attributes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="attributes",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="catalog.productvariant",
            ),
            preserve_default=False,
        ),
    ]
