# Generated by Django 5.2.9 on 2025-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keycapspecification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="switchspecification",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name="KeyboardSpecification",
        ),
        migrations.DeleteModel(
            name="KeycapSpecification",
        ),
        migrations.DeleteModel(
            name="SwitchSpecification",
        ),
    ]
