# Generated by Django 5.2.9 on 2025-12-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_keycapspecification_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.attributevalue"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
