# Generated by Django 5.2.9 on 2025-12-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_attributes_productimage_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="is_main",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
