# Generated by Django 5.2.9 on 2025-12-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_color_productvariant_switch_rename_model_brand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="variant",
        ),
        migrations.AddField(
            model_name="productimage",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.color",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
            ),
            preserve_default=False,
        ),
    ]
