# Generated by Django 5.2.9 on 2025-12-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_productimage_is_main_productvariant_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
